# Site name
name: Sanna Tiihonen
# No trailing slash
url: https://sannatiihonen.github.io
# Reference timezone for time calculations
tz: Europe/Helsinki
# Default language (can be overridden in posts)
lang: fi
# Default image if no post-specific one
image: /images/sanna_default.jpg
# Default author (can be overriden in posts)
author:
  name: Sanna Tiihonen
  email: sanna.tiihonen@iki.fi
